// Wait for the DOM to fully load
// document.addEventListener('DOMContentLoaded', () => {
//     const addButton = document.getElementById('add-task-btn');
//         const taskInput = document.getElementById('task-input');
//             const taskList = document.getElementById('task-list');
//
//                 // Load tasks from localStorage
//                     loadTasks();
//
//                         // Event listener for Add Task button
//                             addButton.addEventListener('click', () => {
//                                     const taskText = taskInput.value.trim();
//                                             if (taskText !== '') {
//                                                         addTask(taskText);
//                                                                     taskInput.value = ''; // Clear input field
//                                                                             } else {
//                                                                                         alert('Please enter a task.');
//                                                                                                 }
//                                                                                                     });
//
//                                                                                                         // Event listener for "Enter" key in input field
//                                                                                                             taskInput.addEventListener('keypress', (event) => {
//                                                                                                                     if (event.key === 'Enter') {
//                                                                                                                                 const taskText = taskInput.value.trim();
//                                                                                                                                             if (taskText !== '') {
//                                                                                                                                                             addTask(taskText);
//                                                                                                                                                                             taskInput.value = '';
//                                                                                                                                                                                         } else {
//                                                                                                                                                                                                         alert('Please enter a task.');
//                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                             }
//                                                                                                                                                                                                                                 });
//
//                                                                                                                                                                                                                                     // Function to add a task
//                                                                                                                                                                                                                                         function addTask(taskText, save = true) {
//                                                                                                                                                                                                                                                 const li = document.createElement('li');
//                                                                                                                                                                                                                                                         li.textContent = taskText;
//
//                                                                                                                                                                                                                                                                 const removeBtn = document.createElement('button');
//                                                                                                                                                                                                                                                                         removeBtn.textContent = 'Remove';
//                                                                                                                                                                                                                                                                                 removeBtn.className = 'remove-btn';
//
//                                                                                                                                                                                                                                                                                         // Remove task from DOM and localStorage
//                                                                                                                                                                                                                                                                                                 removeBtn.onclick = () => {
//                                                                                                                                                                                                                                                                                                             taskList.removeChild(li);
//                                                                                                                                                                                                                                                                                                                         removeTaskFromLocalStorage(taskText);
//                                                                                                                                                                                                                                                                                                                                 };
//
//                                                                                                                                                                                                                                                                                                                                         li.appendChild(removeBtn);
//                                                                                                                                                                                                                                                                                                                                                 taskList.appendChild(li);
//
//                                                                                                                                                                                                                                                                                                                                                         if (save) {
//                                                                                                                                                                                                                                                                                                                                                                     saveTaskToLocalStorage(taskText);
//                                                                                                                                                                                                                                                                                                                                                                             }
//                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                     // Save task to localStorage
//                                                                                                                                                                                                                                                                                                                                                                                         function saveTaskToLocalStorage(taskText) {
//                                                                                                                                                                                                                                                                                                                                                                                                 const tasks = JSON.parse(localStorage.getItem('tasks') || '[]');
//                                                                                                                                                                                                                                                                                                                                                                                                         tasks.push(taskText);
//                                                                                                                                                                                                                                                                                                                                                                                                                 localStorage.setItem('tasks', JSON.stringify(tasks));
//                                                                                                                                                                                                                                                                                                                                                                                                                     }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                         // Remove task from localStorage
//                                                                                                                                                                                                                                                                                                                                                                                                                             function removeTaskFromLocalStorage(taskText) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                     let tasks = JSON.parse(localStorage.getItem('tasks') || '[]');
//                                                                                                                                                                                                                                                                                                                                                                                                                                             tasks = tasks.filter(task => task !== taskText);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                     localStorage.setItem('tasks', JSON.stringify(tasks));
//                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Load tasks from localStorage
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                 function loadTasks() {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const storedTasks = JSON.parse(localStorage.getItem('tasks') || '[]');
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 storedTasks.forEach(taskText => addTask(taskText, false));
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });
//
